name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Verificar Cypress
        run: npx cypress verify

      - name: Instalar dependências do Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64

      # ✅ CORRIGIDO AQUI
      - name: Rodar testes E2E
        run: npx cypress run --spec "cypress/e2e/*.cy.js"
        continue-on-error: true

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Gerar relatório Allure E2E
        if: always()
        run: allure generate allure-results --clean -o allure-report-e2e

      - name: Upload relatório Allure E2E
        uses: actions/upload-artifact@v4
        with:
          name: allure-e2e
          path: allure-report-e2e


  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Verificar Cypress
        run: npx cypress verify

      - name: Rodar testes API
        run: npx cypress run --spec "cypress/e2e/api/**/*.cy.js"
        continue-on-error: true

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Gerar relatório Allure API
        if: always()
        run: allure generate allure-results --clean -o allure-report-api

      - name: Upload relatório Allure API
        uses: actions/upload-artifact@v4
        with:
          name: allure-api
          path: allure-report-api