name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

     
      - name: Instalar dependências do Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64

      # RODAR TESTES (ÚNICO STEP NECESSÁRIO)
      - name: Rodar testes Cypress
        run: npx cypress run

      #  Allure
      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Gerar relatório Allure
        run: allure generate allure-results --clean -o allure-report

      - name: Upload do relatório Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report